__version__ = "0.3.0"
__package__ = "aiu"
__author__ = "Francis Charette Migneault"
__maintainer__ = "Francis Charette Migneault"
__email__ = "francis.charette.migneault@gmail.com"
__description__ = "Tool for updating ID3 tags of audio files using info configuration files."
__url__ = "https://github.com/fmigneault/aiu"
