__version__ = "1.7.2"
__package__ = "aiu"
__author__ = "Francis Charette Migneault"
__maintainer__ = "Francis Charette Migneault"
__email__ = "francis.charette.migneault@gmail.com"
__description__ = "Tool for updating ID3 tags of audio files using text metadata and configuration files."
__url__ = "https://github.com/fmigneault/aiu"
