"""
Package metadata.
"""
__version__ = "2.0.4"
__package__ = "aiu"
__title__ = "Audio Info Updater"
__author__ = "Francis Charette Migneault"
__maintainer__ = "Francis Charette Migneault"
__email__ = "francis.charette.migneault@gmail.com"
__description__ = "Tool for updating ID3 tags of audio files using text metadata and configuration files."
__url__ = "https://github.com/fmigneault/aiu"
